audio_play_node:
  ros__parameters:
    # 本地视频文件绝对或相对路径
    VIDEO_FILE_PATH: "/home/smx/NetworkShare/Video1_4.mp4"
    # 发布的 Image 话题名称
    IMAGE_TOPIC: "SMX/GimbalCamera"
    # 发布帧率 (Hz)
    PUBLISH_FPS: 30

spot_detector_node:
  ros__parameters:
    # 输入图像话题
    IMAGE_INPUT_TOPIC:  "/SMX/GimbalCamera"
    # 标记后发布图像话题
    IMAGE_OUTPUT_TOPIC: "/SMX/TargetImage"
    # 发布角度信息的话题
    ANGLE_OUTPUT_TOPIC: "/SMX/TargetImageAngle"
    # 水平和垂直视场（度）
    FOV_H: 125.0
    FOV_V:  69.0

face_check_node:
  ros__parameters:
    # 订阅的摄像头图像话题
    IMAGE_INPUT_TOPIC: "/SMX/GimbalCamera"
    # 发布识别到的目标分类（人名）
    NAME_OUTPUT_TOPIC:  "/SMX/TargetCategory"
    # 发布标记后图像
    IMAGE_OUTPUT_TOPIC: "/SMX/TargetImage"
    # 发布角度信息
    ANGLE_OUTPUT_TOPIC: "/SMX/TargetImageAngle"
    # 相机视场角（水平, 垂直）
    FOV_H: 125.0
    FOV_V:  69.0
    # 人脸库所在子目录（相对于 package share 目录）
    FACE_LIB_DIRS:
      - "other"
      - "local_file"

drone_detector_node:
  ros__parameters:
    # 输入图像话题
    IMAGE_INPUT_TOPIC: "/SMX/GimbalCamera"
    # 发布角度消息的话题
    ANGLE_OUTPUT_TOPIC: "/SMX/TargetImageAngle"
    # 发布标记后视频图像的话题
    IMAGE_OUTPUT_TOPIC: "/SMX/TargetImage"
    # 模型权重文件路径（相对包 share 目录）
    MODEL_REL_PATH: "resource/drone_model_best_0.pth"
    # 相机视场角（度）
    FOV_H: 125.0
    FOV_V:  69.0