drone_detector_node:
  ros__parameters:
    tracking_topic:   "/yolo/tracking"
    cmd_topic:        "SMX/SportCmd"
    angle_topic:      "SMX/TargetImageAngle"
    image_width:      1280
    image_height:     720
    fov_h_deg:        125.0
    fov_v_deg:        69.0


face_check_node:
  ros__parameters:
    # 订阅的摄像头图像话题
    IMAGE_INPUT_TOPIC: "/SMX/Camera_Raw2"
    # 发布识别到的目标分类（人名）
    NAME_OUTPUT_TOPIC:  "/SMX/TargetCategory"
    # 发布标记后图像
    IMAGE_OUTPUT_TOPIC: "/SMX/TargetImage"
    # 发布角度信息
    ANGLE_OUTPUT_TOPIC: "/SMX/TargetImageAngle"
    # 相机视场角（水平, 垂直）
    FOV_H: 125.0
    FOV_V:  69.0
    # 人脸库所在子目录（相对于 package share 目录）
    FACE_LIB_DIRS:
      - "other"
      - "local_file"

# 相机节点配置
ip_camera_node:
  ros__parameters:
    # 发布的 Image 话题名称
    IP_Camera: "/SMX/Camera_Raw1"

    # Jetson Nano 参数
    # IP_GSTREAMER: >-
    #   rtspsrc location=rtsp://192.168.123.64:554/H264
    #   protocols=GST_RTSP_LOWER_TRANS_UDP latency=50 drop-on-latency=true
    #   ! rtph264depay
    #   ! h264parse
    #   ! nvv4l2decoder enable-max-performance=1 disable-dpb=1
    #   ! nvvidconv output-buffers=1
    #   ! video/x-raw,format=(string)BGRx
    #   ! videoconvert ! video/x-raw,format=BGR
    #   ! appsink sync=false max-buffers=1 drop=true

    # amd64 gpu4060 参数
    IP_GSTREAMER: >-
      rtspsrc location=rtsp://192.168.123.64:554/H264
      protocols=GST_RTSP_LOWER_TRANS_TCP
      latency=150 drop-on-latency=false
      ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=0
      ! rtph264depay
      ! h264parse config-interval=-1
      ! video/x-h264,stream-format=byte-stream,alignment=au
      ! nvh264dec
      ! videoconvert
      ! video/x-raw,format=BGR
      ! appsink sync=false max-buffers=1 drop=true

    pub_camera_raw_enable: true
    pub_camera_compressed_enable: false

spot_detector_node:
  ros__parameters:
    # 输入图像话题
    IMAGE_INPUT_TOPIC:  "/SMX/Camera_Raw1"
    # 标记后发布图像话题
    IMAGE_OUTPUT_TOPIC: "/SMX/TargetImage"
    # 发布角度信息的话题
    ANGLE_OUTPUT_TOPIC: "/SMX/Drone_Target"
    # 水平和垂直视场（度）
    FOV_H: 125.0
    FOV_V:  69.0

usb_camera_node:
  ros__parameters:
    # 摄像头设备号（如 /dev/video0 → 0）
    device_id: 4
    # 发布的话题名称
    image_topic: "/SMX/Camera_Raw2"
    # 发布帧率 (Hz)
    publish_fps: 30

usb_camera_node2:
  ros__parameters:
    # 摄像头设备号（如 /dev/video0 → 0）
    device_id: 0
    # 发布的话题名称
    image_topic: "/SMX/Camera_Raw3"
    # 发布帧率 (Hz)
    publish_fps: 30

video_play_node:
  ros__parameters:
    # 本地视频文件绝对或相对路径
    VIDEO_FILE_PATH: "/home/unitree/WorkSpace/Video/Video2_3.mp4"
    # 发布的 Image 话题名称
    IMAGE_TOPIC: "SMX/GimbalCamera_Raw"
    # 发布帧率 (Hz)
    PUBLISH_FPS: 30

yolo_obb_node:
  ros__parameters:
    model_path: /home/smx/WorkSpace/GDS_LeggedRobot/src/Ros2ImageProcess/yolo_obb/resource/best.pt
    image_topic: /SMX/Camera_Raw1
    image_qos: reliable
    imgsz: 640
    conf: 0.3
    device: cuda:0
    half: true
    draw: true
    target_names: ["person", "drone"] 
    pitch_ratio_k: 0.4
    uav_width_m: 0.45
    fov_h_deg: 66.0
    fov_v_deg: 44.0
    gimbal_angle_topic: /SMX/GimbalState
    vehicle_odom_topic: /SMX/Odom_gimbal
    gimbal_location: [0.0,0.0,0.34]
    gimbal_orientation: [0.0,0.0,0.0]
    output_image_topic: /SMX/TargetImage1
    # 消息格式： 观测点位置在label中，发布检测到的所有目标在data中，每个目标有对应的“相对于观测点的偏航角”、“相对于观测点的俯仰角”、“相对观测点的距离”、“图像中的滚转角”、“图像中的俯仰角”、“检测置信度”
    output_obs_topic:  /SMX/Drone_Target 

    rviz_enable: true
    rviz_model:  "mesh"
    rviz_scale: [0.02, 0.02, 0.02]
    rviz_color: [0.0, 1.0, 0.5, 1.0] 
    rviz_mesh_resource: "package://yolo_obb/resource/Telescope.stl"
    rviz_ns: "yolo_obb"

yolo_obb_node2:
  ros__parameters:
    model_path: /home/smx/WorkSpace/GDS_LeggedRobot/src/Ros2ImageProcess/yolo_obb/resource/best.pt
    image_topic: /SMX/Camera_Raw2
    image_qos: reliable
    imgsz: 640
    conf: 0.3
    device: cuda:0
    half: true
    draw: true
    target_names: ["person", "drone"] 
    pitch_ratio_k: 0.4
    uav_width_m: 0.45
    fov_h_deg: 98.24
    fov_v_deg: 67.1
    gimbal_angle_topic: /SMX/Gimbal_ATP2
    vehicle_odom_topic: /SMX/Odom_ATP2
    gimbal_location: [-3.38,0.0,0.9]
    gimbal_orientation: [0.0,0.5235,0.0] #2.37 1.57 0.79
    output_image_topic: /SMX/TargetImage2
    output_obs_topic:  /SMX/Drone_Target

    rviz_scale: [0.02, 0.02, 0.02]
    rviz_color: [0.0, 1.0, 0.5, 1.0] 
    rviz_mesh_resource: "package://yolo_obb/resource/Telescope.stl"
    rviz_ns: "yolo_obb2"

yolo_obb_node3:
  ros__parameters:
    model_path: /home/smx/WorkSpace/GDS_LeggedRobot/src/Ros2ImageProcess/yolo_obb/resource/best.pt
    image_topic: /SMX/Camera_Raw3
    image_qos: reliable
    imgsz: 640
    conf: 0.3
    device: cuda:0
    half: true
    draw: true
    target_names: ["person", "drone"] 
    pitch_ratio_k: 0.4
    uav_width_m: 0.45
    fov_h_deg: 98.24
    fov_v_deg: 67.1
    gimbal_angle_topic: /SMX/Gimbal_ATP3
    vehicle_odom_topic: /SMX/Odom_ATP3
    gimbal_location: [-3.38,-1.97,0.85]
    gimbal_orientation: [0.0,0.5235,0.79]
    output_image_topic: /SMX/TargetImage3
    output_obs_topic:  /SMX/Drone_Target

    rviz_scale: [0.02, 0.02, 0.02]
    rviz_color: [0.0, 1.0, 0.5, 1.0] 
    rviz_mesh_resource: "package://yolo_obb/resource/Telescope.stl"
    rviz_ns: "yolo_ob3"
